### ISSUE TITLE
Webapp interface breaks out of environment into browser when following any route. 

### ISSUE THREAD

**Issue by qjr3** [qjroundy/MigraineTracker#11]
Open site from home screen the site is locked in a interface-less browser (all safari features are hidden and inaccessible). This is desired across whole site however it breaks out of this when following any link. will upload images later.

**Comment by johnslay** [comment]
how is it now?

**Comment by qjr3** [comment]
has it been pushed to the live dev site? If so I'll run some tests on all my devices later tonight (about an hour from now)

**Comment by johnslay** [comment]
na im asking if its still an issue? cause it works fine for me

**Comment by qjr3** [comment]
Needs to be tested on a live site before closing issue.

**Comment by johnslay** [comment]
where are you seeing this issue? im not seeing this on any device of mine

**Comment by qjr3** [comment]
ipod, ipad iOS 9.0.2 with safari

**Comment by qjr3** [comment]
Sorry, I had mentioned it to you in person and showed you so I forgot to add it here.

**Comment by qjr3** [comment]
I have just tested and it seems to work correctly now.
