### ISSUE TITLE
Created new journal, edit not populating correctly

### ISSUE THREAD

**Issue by michaelkimball** [qjroundy/MigraineTracker#37]
I pulled the newest code at 12:45AM 18 November 2015
Created a new journal
![selection_025](https://cloud.githubusercontent.com/assets/14002337/11234469/cee8a118-8d8d-11e5-8343-83454214d89b.png)

Went to edit and it nulled out some fields
![selection_026](https://cloud.githubusercontent.com/assets/14002337/11234484/ed5a1988-8d8d-11e5-9961-2ac99b625066.png)

It is an improvement from what I was getting from the faker data however.

**Comment by qjr3** [comment]
The only ones i'm not getting to persist are Missed social and missed others. Probably because I just un-disabled those and forgot something. I'll look at those later. But for me the other ones are persisting.

**Comment by qjr3** [comment]
I forgot when I re-enabled those fields that they had their names changed in the database. I updated them in teh view and it should now work.
