### ISSUE TITLE
No authentication for journals

### ISSUE THREAD

**Issue by johnslay** [qjroundy/MigraineTracker#8]
Currently, there is no authentication for when a user tries to access another users journal log. 
You will get 404 error in the case of viewing any journal not created by the owner. We should either implement a redirect or a custom 404 page.

**Comment by qjr3** [comment]
my recommendation is a redirect or basically....get the f*ck off my page and go back to where you belong......direct. :) I noticed this earlier too, but I haven't looked into it.

**Comment by qjr3** [comment]
fixed with issue-#8-fix
